### ISSUE TITLE
[FR] Logs

### ISSUE THREAD

**Issue by SaphireVert** [SaphireVert/gitlabot#5]
Lorsque le bot est en fonctionnement, il n'y a pas beaucoup de logs, il serait bien de rajouter un middleware qui permet de faire des logs propres du bot (winston)

**Comment by ponsfrilus** [comment]
→ https://github.com/winstonjs/winston
Voir aussi cette issue sur Telebot [https://github.com/mullwar/telebot/issues/185](https://github.com/mullwar/telebot/issues/185).

**Comment by SaphireVert** [comment]
> → https://github.com/winstonjs/winston
> Voir aussi cette issue sur Telebot [mullwar/telebot#185](https://github.com/mullwar/telebot/issues/185).

Yep, je note merci !

**Comment by SaphireVert** [comment]
Closed by Closed by 45dc58e

**Comment by SaphireVert** [comment]
Closed by Closed by 45dc58e
