### ISSUE TITLE
[FR] Lisibilité des messages

### ISSUE THREAD

**Issue by SaphireVert** [SaphireVert/gitlabot#7]
Les messages de réponse que le bot nous envoie ne sont pas toujours très lisibles (manque de mise en forme), ce serait bien de pouvoir l'améliorer

**Comment by ponsfrilus** [comment]
Il faut aussi les uniformiser : enlever le numéro de version lorsqu'il n'est pas nécessaire, utiliser le même formattage partout, ajouter la date des posts, etc...

**Comment by SaphireVert** [comment]
Closed by 0bbe3eb
