### ISSUE TITLE
[FR] Faire correspondre les tags git avec les numéros de versions

### ISSUE THREAD

**Issue by ponsfrilus** [SaphireVert/gitlabot#8]
Chaque numéros de version (i.e. dans [package.json](./package.json)) doit correspondre à un tag git et potentiellement un "release" sur github.

Plus généralement, une "target" du [Makefile](./Makefile) doit pouvoir gérer cela automatiquement.

**Comment by SaphireVert** [comment]
Done, closed since v0.0.5
